import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx('h-screen w-screen', inter.className)}>
        <div>
          <nav className="flex h-min bg-slate-100 p-4">
            <Link href="/">Auto-Task</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
